apiVersion: v1
kind: Service
metadata:
  name: calc-server
  namespace: default
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    run: calc-server
  type: LoadBalancer
